### ISSUE TITLE
Enhance figures in DDA quant module

### ISSUE THREAD

**Issue by wolski** [Proteobench/ProteoBench#104]
- Write figure captions (description).
- Integrate them into the DDA quant page.
- Review axis labels.

**Comment by mlocardpaulet** [comment]
for axis label in the density plot, instead of "1/2" we could write "measured ration (condition A/condition B)", then what I don't know is: is it a mean of replicates? Or is it all ions/peptidoforms? I would need to check.

**Comment by mlocardpaulet** [comment]
I added information around the figure, do you think that we should add more?

**Comment by mlocardpaulet** [comment]
Shall we make the horizontal (y = 0) and vertical axis (x = 0) black lines? I think that it would be good to see them more.

**Comment by RobbinBouwmeester** [comment]
This is done? @mlocardpaulet

**Comment by mlocardpaulet** [comment]
the issue is solved but we did not address the comment of the 21st of december (if we want to make the change):
> Shall we make the horizontal (y = 0) and vertical axis (x = 0) black lines? I think that it would be good to see them more.

**Comment by wolski** [comment]
Looking into figures just now. Also wanted to add a figure with the CV. I will create a pull request later this week.
