### ISSUE TITLE
Coloring functionality based on user input

### ISSUE THREAD

**Issue by carolinelennartsson** [Proteobench/ProteoBench#107]
New feature that allows the user to select a parameter and color points on the plot based on the parameter value.

**Comment by carolinelennartsson** [comment]
I don't think this issue is fully closed yet. I made a feature to view the dataset table and color points on the plot based on the table. We would need some restrictions on the table, if we choose to keep it like this.

**Comment by mlocardpaulet** [comment]
this is great. It works well when I select points in the table that plots when we open ProteoBench. 
But when I upload a benchmark run, and there is a new plot with the additional point, then if I select a row the table disappears.

**Comment by mlocardpaulet** [comment]
For now it works OK. We can reopen this issue in the futur if we want something more sophisticated.
