### ISSUE TITLE
Missing identifications cause parser to crash

### ISSUE THREAD

**Issue by straussmaximilian** [Proteobench/ProteoBench#11]
Hi,
I uploaded my full sample, and this works fine.
Then I reduced the file size by taking every n-th point. This works for 2 and 4, but there is a crash at 8.
I would guess this is because some identifications are missing, so we should probably build in some safeguards for that.

<img width="743" alt="Screenshot 2023-02-08 at 10 11 25 AM" src="https://user-images.githubusercontent.com/16521288/217485569-625eb663-bdee-4db3-bef4-2df362456f05.png">

Minimal sample to reproduce is attached.
[results_peptides_subset_32.csv](https://github.com/Proteobench/Proteobench/files/10683751/results_peptides_subset_32.csv)

**Comment by RobbinBouwmeester** [comment]
Not a problem in current version.
