### ISSUE TITLE
cutoff values for datapoints

### ISSUE THREAD

**Issue by viikiid** [Proteobench/ProteoBench#115]
we do not want to decide (yet) which cutoff value is the best, so we decided to add all 5 different cutoff values as datapoints to the json file
things to do:

- add a flag to each datapoint which cutoff value it is
- add all possible datapoints to json

**Comment by RobbinBouwmeester** [comment]
To clarify this is the cutoff value for being at least quantified in x number of runs.

**Comment by RobbinBouwmeester** [comment]
Fixed in #175
