### ISSUE TITLE
create a contact email that will be visible on the website and documentation

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#120]
I guess that it would send an email to me for the time being, or me and Robbin if he'd like.

**Comment by RalfG** [comment]
I added an email alias [proteobench@eubic-ms.org](mailto:proteobench@eubic-ms.org) that forwards to @mlocardpaulet and @RobbinBouwmeester. Let me know if that should be changed.

**Comment by mlocardpaulet** [comment]
add link to the email to the website/documentation

**Comment by RobbinBouwmeester** [comment]
@mlocardpaulet could you add proteobench@eubic-ms.org?

**Comment by mlocardpaulet** [comment]
I would. I just don't really know how to do it 😅 Let me find out!

**Comment by mlocardpaulet** [comment]
OK, done here: PR #218
