### ISSUE TITLE
add link to the fasta file in the module DDA quant

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#139]

**Comment by mlocardpaulet** [comment]
@RobbinBouwmeester we need to do this before we start testing the webplatform. I just don't remember where I need to put the fasta 🐸

**Comment by RobbinBouwmeester** [comment]
@julianu can we put this on your server?

If not too big we can put it (maybe zipped) on a github repo. For the repo I would suggest the results repo the fasta is linked to.

**Comment by julianu** [comment]
Sure, it can go on the server.
Is there a way to add static content to streamlit (would be the easiest solution).

**Comment by RobbinBouwmeester** [comment]
Yes, that is possible: https://docs.streamlit.io/library/advanced-features/static-file-serving

Can you implement this or shall I have a stab at it @julianu?

**Comment by julianu** [comment]
I can do this.
The FASTA is the one in the PRIDE repo?

**Comment by mlocardpaulet** [comment]
> I can do this. The FASTA is the one in the PRIDE repo?

Nope. You can find it here: https://github.com/Proteobench/Results_Module2_quant_DDA/blob/main/Fasta/ProteoBenchFASTA_DDAQuantification.fasta

**Comment by mlocardpaulet** [comment]
Hey @julianu! this looks super great! 
Although... the zip file opens in a new tab and is pretty unreadable. And if I right-click, I don't find how to download.

**Comment by julianu** [comment]
I hoped, it was due to my browser settings.
But I found something, trying to make it behave like a "normal" download.

**Comment by julianu** [comment]
The PR #207 should have fixed it.
