### ISSUE TITLE
rename the modules

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#141]
The current naming of the issues will become an issue fairly quickly. For example, "DDA_quan" is not specific enough since we want to have one module at peptidoform level and another one at ion level. And we may have one per instrument type... It can get messy pretty quickly.
Also, I suggest to get them numbers or some kind of unique identifier that would be easy to reference/keep track of to be able to identify modules (new ones, active ones, archived ones...) without any ambiguity.

**Comment by scaramonche** [comment]
One can partly solve this by using the `st_pages` package and a `pages.toml` file for the page names, etc. See also issue #147, which is related.
