### ISSUE TITLE
DDA quant module: custom input format - how about modifications?

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#144]
currently, we give these information for upload in custom format: 
```
You can use the tab-delimited Custom format containing the following columns:
- Sequence: peptide sequence
- Proteins: Protein accessions according to fasta file
- Charge: Charge state of measured peptide
- FQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01: Quantitative column sample 1
- LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02: Quantitative column sample 2
- LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03: Quantitative column sample 3
- LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01: Quantitative column sample 4
- LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02: Quantitative column sample 5
- LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03: Quantitative column sample 6
```
What about modifications? They need to be encoded somewhere, right? I think that the best option would be a dedicated column, it needs to be decided.

**Comment by RobbinBouwmeester** [comment]
Indeed either a different column or a modified sequence. Either would work. I think modified sequence (whatever format) is probably the most common.

**Comment by mlocardpaulet** [comment]
I guess that we just need to decide to be able to give clear instructions to users. 
The only disadvantages that I see with modified sequence over modification column are:
1. I am not sure it is always provided, and I believe that it may be more difficult to generate than to add a column with modifications identifiers.
2. the issue of non-localised PTMs (again). I don't know how this is handled by software tools when generating the modified sequences. And since this is what we use for counting the number of identifications, it can become an issue.

**Comment by RobbinBouwmeester** [comment]
The thing is that non-localized PTMs will be an issue in both ways of formatting.

What we could do is have two custom formats, one with modified sequence one with a separate column. I would argue that modified sequence is probably fine for now. Especially if we indicate it should be proforma compliant.

**Comment by mlocardpaulet** [comment]
Sure. I think that we have to make it simple for us. In any cases, we don't plan to allow public upload for custom formats. So we can give a lot of freedom. 
We just have to provide complete instructions. 
And I am not sure that this is currently possible to load custom data, is it?

**Comment by mlocardpaulet** [comment]
I can modify the instructions to clarify. I will just need to know how we parse the data to make sure that it is aligned.
