### ISSUE TITLE
parse Proline parameters

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#145]
Hi, 
these are the information that David sent me on how to find the parameters in Proline. Proline outputs are excel files. Until now we only used the txt exports of one of the sheet (the one with the precursor-level information), but I think that we should change it so that we should change it so that users should upload the excel file. Then we'll have all the information in it. 
I plan to get some test files when I come back. @enryH If you want to work on it in the mean time, let me know. I will ask Emmanuelle in Toulouse to start some searches with our raw files and fasta. This way she will have everything ready for testing as soon as the tool is ready :)

[ProteoBench Proline parameters mapping.xlsx](https://github.com/Proteobench/ProteoBench/files/13493605/ProteoBench.Proline.parameters.mapping.xlsx)

**Comment by mlocardpaulet** [comment]
Hey @enryH ! I submitted 3 public data sets for upload, with the associated parameters (one of them is the one in the cloud). They were successfully saved in the module github repo., in the json file. But the MBR parameter was not parsed correctly. They all were done with MBR but all have "FALSE".

**Comment by mlocardpaulet** [comment]
Also, there is an issue with parsing the search engine version:
`"search_engine_version":null`, whereas it should be `X! Tandem Vengeance (2015.12.15.2)` or `Vengeance (2015.12.15.2)` or `2015.12.15.2`?

**Comment by enryH** [comment]
The MBR/cross alignment parsing was an error ( I did not update the sheet). I hope the logic is still correct. 

The `software_version` was indeed actually the `search_engine_version`.  I pick it up from the first sheet "Search settings and infos".
