### ISSUE TITLE
always use light mode

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#150]
I think that the plot is difficult to see in dark mode. Also, it makes our life more complicated for the logos. So I would suggest to force light mode.

**Comment by scaramonche** [comment]
As far as I could see one needs to create a `config.toml` file in the `webinterface/.streamlit/` directory and add the following setting to it:
```
[theme]
base="light"
```
@RobbinBouwmeester, I assume this could be done on the deployment server and I am not sure if it needs to be in the github repo of ProteoBench. What do you think?
