### ISSUE TITLE
histogram colors are not consistent

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#154]
when plotting the first histogram (log2-FCs for the different species), the colors do not always corespond to the same species. For example, today I have:
human = dark blue
yeast = blue
e. coli = red
for an msfragger import, and:
human = dark blue
e. coli = blue
yeast = red

It is not a big issue but it would be better to always have the same color for the same species

**Comment by wolski** [comment]
Should we add the color information to the module settings toml? For instance?

```
[species_expected_ratio]
[species_expected_ratio.YEAST]
"A_vs_B" = 2.0
"color" = "red"
[species_expected_ratio.ECOLI]
"A_vs_B" = 0.25
"color" = "blue"
[species_expected_ratio.HUMAN]
"A_vs_B" = 1.0
"color" = "green"

[General]
min_count_multispec = 1

**Comment by mlocardpaulet** [comment]
> Should we add the color specification to the module_settings.tool? For instance:
> 
> ```
> [species_expected_ratio]
> [species_expected_ratio.YEAST]
> "A_vs_B" = 2.0
> "color" = "red"
> [species_expected_ratio.ECOLI]
> "A_vs_B" = 0.25
> "color" = "blue"
> [species_expected_ratio.HUMAN]
> "A_vs_B" = 1.0
> "color" = "green"
> 
> [General]
> min_count_multispec = 1
> ```

I think that this is a good idea :)

**Comment by wolski** [comment]
closed by pull request 180
