### ISSUE TITLE
Separate unit from value for the mass_tolerance when parsing meta parameters file 

### ISSUE THREAD

**Issue by scaramonche** [Proteobench/ProteoBench#165]
Currently the parsing has it together while in the additional parameters of the page and datapoint, they are separate variables. We need to fix this to be consistent.

**Comment by enryH** [comment]
Hey. @mlocardpaulet and I agreed to join it when working on #58. [sdrf-pipelines](https://github.com/bigbio/proteomics-sample-metadata/blob/master/sdrf-proteomics/assets/parahttps://github.com/bigbio/proteomics-sample-metadata/blob/b41102d12534c64396a087c6e1bd31b1ae7b3dc3/sdrf-proteomics/assets/param2sdrf.yml) combined it, see [Lines 18ff](https://github.com/bigbio/proteomics-sample-metadata/blob/b41102d12534c64396a087c6e1bd31b1ae7b3dc3/sdrf-proteomics/assets/param2sdrf.yml#L18-L26).  Therefore we decided to combine the two values (see [old table](https://docs.google.com/spreadsheets/d/1Os3By8LYuVGcfH65X2-9tSjJnmtH-nL03tPYLtPOj-c/edit#gid=0)).

So this should be either displayed as is or if you need it separated, the logic has to be implementend in the app. Should be as simple as a `str.split` and a conversion to `float` of the values. Where will you need it?

**Comment by enryH** [comment]
So to be consistent the app has to be updated:/

**Comment by scaramonche** [comment]
OK, fair enough! I will look into it.

**Comment by scaramonche** [comment]
Addressed in #169.
