### ISSUE TITLE
new point does not appear unless we move the slidebar

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#181]
the new point does not appear. First, the plot is empty (or only contains the public points but there are none for now). I think that it comes from the moment we added the slidebar. When we change the value of the slidebar, then the point appears.
Also, could we make the slidebar black and not red? Because "YEAST" is red in the plot just above and it can be confusing.

**Comment by RobbinBouwmeester** [comment]
Sure, will have a look. It actually has to do with new file uploads. It is additive currently (new figures + upload menus each time you upload), but the slidebar resets that.

**Comment by RobbinBouwmeester** [comment]
Bug introduced after ac2b97c79f1ffdb8609e4150fdd74229c9d8aaa9

**Comment by RobbinBouwmeester** [comment]
Issue introduced here: f55f0a36faa360d09f0ceb8ce881657a495e542a#diff-fa548dc69d46b82fa4d6f6377c871e16164210c540b30b3350f8858e70809d29

Instead of reverting, new PR and merge, see #185

**Comment by RobbinBouwmeester** [comment]
The median_abs_epsilon is now not being calculated... At least until slider is moved.

**Comment by RobbinBouwmeester** [comment]
Should be fixed in #186
