### ISSUE TITLE
Acknowledgement of de.NBI cloud

### ISSUE THREAD

**Issue by julianu** [Proteobench/ProteoBench#183]
Nothing technical, but I was just informed at another project, that we should acknowledge de.NBI somewhere for the hosting, e.g. in an impressum or footer.
And in a publication, something like this link should be added:
https://cloud.denbi.de/wiki/citation_and_publication/#citation-information

**Comment by mlocardpaulet** [comment]
Of course! I can add it. I'll do that quick :)
So I put this?
‘This work was supported by the BMBF-funded de.NBI Cloud within the German Network for Bioinformatics Infrastructure (de.NBI) (031A532B, 031A533A, 031A533B, 031A534A, 031A535A, 031A537A, 031A537B, 031A537C, 031A537D, 031A538A)'
Can I remove the last part for ProteoBench? '(031A532B, 031A533A, 031A533B, 031A534A, 031A535A, 031A537A, 031A537B, 031A537C, 031A537D, 031A538A)'

And you may have to remind me for the publication.

**Comment by julianu** [comment]
These are the "real" grant numbers of the BMBF. But yes, leave them out on the home page and poster. But please keep them in a manuscript.

**Comment by mlocardpaulet** [comment]
Actually, maybe for the home page I can be a bit more specific and add under the logos:
"This site is hosted by the BMBF-funded de.NBI Cloud within the German Network for Bioinformatics Infrastructure (de.NBI)"
?
You decide really, I'll do as you say

**Comment by julianu** [comment]
Yes, that sounds good for the homepage 👍
