### ISSUE TITLE
no update of previous points when not moving slidebar

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#189]
When I run several times with the same input (here a MQ table, in blue), the points do not overlay (they should). It is corrected when I move the slidebar "Minimal ion quantifications (# samples)" again.
I think that it may be linked to the issue #181 but I am not sure.

Here is a screenshot after a few runs. The 2 blue points should overlay. The big one is in the wrong location and I think that it corresponds to Minimal ion quantifications (# samples) = 3, the default. 

<img width="1037" alt="image" src="https://github.com/Proteobench/ProteoBench/assets/8386272/1a38cd10-9918-428f-88b1-ffe90f34b1dd">

**Comment by RobbinBouwmeester** [comment]
Looking into this right now, I have an idea of how to fix this.

**Comment by RobbinBouwmeester** [comment]
Fixed in #193
