### ISSUE TITLE
make easy to access table with all public benchmark runs

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#197]
It should be possible to find a table containing the information in the json of the public benchmark runs. Ideally, it would also contain the free text comment that can be added when submitting. This way, if some parameters are not automatically parsed by ProteoBench but is important (at least in the opinion of the person submitting it), it is still possible to access it.

**Comment by julianu** [comment]
I will work on this and implement a table below the charts. In this table probably also any additional information of the run can be shown. If also the hash is added, it would solve the issue #209 . Though there it would be nicer to also add the human readable name of the dataset.

**Comment by julianu** [comment]
I am working on this for a single module.
Right now, I  implement a table below the charts. In this table probably also any additional information of the run can be shown. If also the hash is added, it would solve the issue #209 . Though there it would be nicer to also add the human readable name of the dataset.

This could be enhanced for all data, will try to keep this in mind for the code.

Probably this way of download would also solve #174

**Comment by RobbinBouwmeester** [comment]
@julianu would it be easier if the folder name is the "id" instead of the hash of the intermediate?

**Comment by julianu** [comment]
That would not matter much, it's just reading out another field.Let's keep the hash for now.

**Comment by mlocardpaulet** [comment]
> That would not matter much, it's just reading out another field.Let's keep the hash for now.

I guess the idea was to have something more human readable, right? I think that for this the id is better than the hash

**Comment by RobbinBouwmeester** [comment]
Sure, but it is more about the folder names, what we display in the table should definitely be the id and not the hash.

**Comment by RobbinBouwmeester** [comment]
Seems to be available in #239, @mlocardpaulet does this suffice, at least for now?

**Comment by julianu** [comment]
Agree, looks good. I would integrate the download of the "raw" uploads into this table as well.
