### ISSUE TITLE
some parameters should be float but are text

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#212]
some of the parameters are still text but should be floats:

"ident_fdr_peptide":"0.01",
"ident_fdr_protein":"0.01",
"allowed_miscleavages":"1",
"min_peptide_length":"7",
"max_precursor_charge":"7"

It only concerns the last point generated (the one "old_new":"new"). The others are fine.

**Comment by enryH** [comment]
Where did you find these lines?

**Comment by mlocardpaulet** [comment]
You are right, it is not in the final results.json. I got confused when I merged Proteobot -> ProteoBench. It is when I noticed it, in the diff of the PR. But I think that it is nothing then. I'll close the issue and let you know if/when I see it again. But I suspect that it is nothing then. Sorry to have bothered you with nothin.

**Comment by enryH** [comment]
Inquiete:)
