### ISSUE TITLE
modification of the "additional parameters" field

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#232]
Co-workers started using ProteoBench locally and have issues when comparing benchmark runs because none of the parameters that we chose for the `Additional parameters` field change between the runs that they compare. Mostly the differences are:
- MBR parameters
- rescoring
- validation (using Percolator or not...)

So I have been asked to add a free text field. I think that it makes sense. We already discussed this in a previous meeting where @RobbinBouwmeester pointed out that two Proline points had different axis and the same exact parameters reported when hovering. 
To solve this, we decided to report also the "comments" field for publicly available benchmark runs, but we may want to have the equivalent for the additional parameters?

**Comment by RobbinBouwmeester** [comment]
Yes, working on this in #225

**Comment by RobbinBouwmeester** [comment]
Comments can now also be added to "local" submissions
