### ISSUE TITLE
Add warning on good practice in the Module webpage

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#238]
### Discussed in https://github.com/orgs/Proteobench/discussions/237

<div type='discussions-op-text'>

<sup>Originally posted by **mlocardpaulet** February  8, 2024</sup>
There is no way to check the data publicly uploaded to ProteoBench. Currently, the only thing that we can do is to save the parameter files associated with the benchmark runs, so that we can reproduce them. 
This may not be enough... And it has been discussed a lot among us. 
We need to add a warning in the Module, such as the one in the documentation:
```
This module is not designed to compare later-stages post-processing of quantitative data such as missing value replacement, and we advise users to publically upload data without replacement of missing values and without manual filtering.
```
We also need to discuss with the developers of the tools that we make compatible with ProteoBench to be sure that a maximum of the parameters can be retrieved from their ProteoBench-compatible parameter files.</div>

**Comment by RobbinBouwmeester** [comment]
So this can be closed?
