### ISSUE TITLE
add .vscode/settings.json in the .gitignore?

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#245]
Hey, each time I pull the repository, I have a chante in the .vscode/settings.json (see snapshot):
<img width="671" alt="image" src="https://github.com/Proteobench/ProteoBench/assets/8386272/488be9ab-8f13-4324-9f85-498c0fd7c603">
I suspect that it is in my vscode settings. Shouldn't we add this file in the .gitignore? Or the .vscode/ folder?

**Comment by RobbinBouwmeester** [comment]
For dev purposes, people preferred to keep the settings file in the repo. This allowed for specific settings to debug in vscode to be preshared.

**Comment by enryH** [comment]
If you would add the already commited file to the `.gitignore`, it won't igonore it. You would need to remove it from you local index: ` git update-index --assume-unchanged <file>` (https://stackoverflow.com/a/28497505)
