### ISSUE TITLE
Add a version tag on page(s) 

### ISSUE THREAD

**Issue by julianu** [Proteobench/ProteoBench#267]
Now, that we have automated updates on the server, we should put a little version tag on one of the pages (mainpage?), to see whether everything works alright.
Or is it already there and I miss it?

**Comment by mlocardpaulet** [comment]
as discussed in our meeting, we could consider adding the version tag on the figure for traceability.

**Comment by mlocardpaulet** [comment]
PR #295 added the version on the docs (thanks a lot @enryH).
Do you think that this is fine or shall we also have it somewhere on the main page and/or the figures?

**Comment by RobbinBouwmeester** [comment]
Add version in the sidebar. Unknown location to get version, but this seems to work:

`"""ProteoBench"""

from importlib.metadata import version

__version__ = version("proteobench")`

**Comment by wolski** [comment]
It seems this issue was adressed already

<img width="760" alt="image" src="https://github.com/user-attachments/assets/bd1b7e43-76f8-45a6-8fa8-267c47e66000">
