### ISSUE TITLE
Request for FragPipe Parameter File Upload Feature

### ISSUE THREAD

**Issue by jacobfh1** [Proteobench/ProteoBench#273]
Hi team,

I recently tried your DDA Quantification tool at: https://proteobench.cubimed.rub.de/DDA%20Quant%20Ion%20Level%20-BETA-

I used the data generated from FragPipe, which worked great. Instead of manually inserting various parameter settings, it would be great to be able to upload the FragPipe parameter file as suggested at https://proteobench.readthedocs.io/en/latest/modules/3-DDA-Quantification-ion-level/.

Could you provide an update on the progress of this feature?

Best,
Jacob

**Comment by RobbinBouwmeester** [comment]
Hi Jacob,

I believe this should be fixed: https://github.com/Proteobench/ProteoBench/pull/264

@enryH, can you comment?

Kind regards,

Robbin

**Comment by enryH** [comment]
Dear Jacob,

as Robbin points out it should be implemented. However, there are maybe two issues:

### 1. Documentation

I see that the documentation is confusing. 

>Upload “combined_ion/modified_peptides.tsv” in order for Proteobench to calculate the ion ratios. Parameter files are not yet implemented in ProteoBench, but we are working on it. For public submission, please provide the “.params” and the “.worflow” files that correspond to your search.

So we need to delete the third sentence. (@mlocardpaulet , I can do that ). 

It's the first tool which needs two files.

### 2. Deployment

Skimming the deployed version, I think that this is not based on the current main branch. How does the update of the webserver work? (@julianu)

Best, Henry

**Comment by mlocardpaulet** [comment]
> Dear Jacob,
> 
> as Robbin points out it should be implemented. However, there are maybe two issues:
> 
> ### 1. Documentation
> I see that the documentation is confusing.
> 
> > Upload “combined_ion/modified_peptides.tsv” in order for Proteobench to calculate the ion ratios. Parameter files are not yet implemented in ProteoBench, but we are working on it. For public submission, please provide the “.params” and the “.worflow” files that correspond to your search.
> 
> So we need to delete the third sentence. (@mlocardpaulet , I can do that ).
> 
> It's the first tool which needs two files.
> 
> ### 2. Deployment
> Skimming the deployed version, I think that this is not based on the current main branch. How does the update of the webserver work? (@julianu)
> 
> Best, Henry

Hi! Yes, sorry @enryH I missed this. Please delete what is wrong and add more information if public upload is not clear.
And yes, the current version on the server does not correspond to the latest main.

**Comment by enryH** [comment]
I created the PR yesterday, but then we need a stable release (main branch) for the current documentation which is deployed, and a latest release branch with the newest features available.

**Comment by julianu** [comment]
Sorry for the late answer: the web server performs an update as soon as a new version is releases (it is in the same GitHub action).

**Comment by RobbinBouwmeester** [comment]
@enryH, I can make a new release if that would help
