### ISSUE TITLE
Error when several times switching between Home and "DDA Quant"

### ISSUE THREAD

**Issue by wolski** [Proteobench/ProteoBench#281]
I observed that when switching between Home and "DDA Qaunt ... " several times
e.g. Home -> DDA Quant -> Home -> DDA Quant -> Home -> DDA Quant this leads to:

<img width="354" alt="image" src="https://github.com/Proteobench/ProteoBench/assets/1926513/2be11708-4020-42a2-b83a-d8cc7ba09d7e">
<img width="1275" alt="image" src="https://github.com/Proteobench/ProteoBench/assets/1926513/b16aaad5-f49c-4141-afde-c8b2ed916e61">

Reproduced on my local installation as well as on the server.
https://proteobench.cubimed.rub.de

**Comment by vedran-kasalica** [comment]
Was this issue resolved? I tried to reproduce it both locally and on the server, as it appeared somewhat similar to https://github.com/Proteobench/ProteoBench/issues/286, however, I couldn't reproduce it even after switching 15+ times.
