### ISSUE TITLE
modification parsing: missing ")" and "]"

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#282]
**Describe the bug**
The parsing of the modification and reporting in the intermediate table is not right (in the field precursor ion).

**To Reproduce**
1. load a MQ evidence file
2. Click on "parse and bench"

**Expected behavior**
the modifications in the following screenshot should be "[Oxidation (M)]"

**Screenshots**
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/48a594b8-aaa3-4152-9be3-f56644057815)

**Desktop (please complete the following information):**
 - OS: MasOS Sonoma 14.2.1
 - Browser Chrome Version 123.0.6312.122 (Official Build) (arm64)

**Comment by RobbinBouwmeester** [comment]
So, this is due to differences in how to format this, this is what it was in the "old" file format:

_(ac)ADDIDIEAM(ox)LEAPYK_

So best solution is when selecting a software tool we have two entries for MQ, with both formatting options.

**Comment by mlocardpaulet** [comment]
I see, yes. This is a bit annoying!
How do you want to proceed? 
Shall we:
1. have several "MaxQuant" options in the drop-down menue of the upload: like "MaxQuant version 1.5 to 2.4" and "MaxQuant version 2.5 or above"
2. make a more general "modification sequence format" dropdown menu that comes up after the workflow tool selection. This option is more flexible but means that the user has to check him/herself.
3. check automatically what format the modified sequence is using, but not sure how easy/reliable this can be.

**Comment by RobbinBouwmeester** [comment]
I think option one is the easiest. But the other options are definitely also possible.

**Comment by mlocardpaulet** [comment]
Let's do that then.

**Comment by RobbinBouwmeester** [comment]
Ok, I think I have a different better solution in mind, with a "greedy" regex. Will try this and keep you posted.

**Comment by RobbinBouwmeester** [comment]
Could you check #299 @mlocardpaulet

**Comment by RobbinBouwmeester** [comment]
Should now finally be fixed in #324
