### ISSUE TITLE
Error during submission of FragPipe output/FragPipe - MSFragger version number

### ISSUE THREAD

**Issue by brvpuyve** [Proteobench/ProteoBench#285]
Hi all,

When I tried to submit the output of FragPipe, I received an error message:
![image (2)](https://github.com/Proteobench/ProteoBench/assets/35368580/efe552b8-b289-4b82-a120-f5cad25dac9a)
It seems the issue is specifically related to the parameter files as the submission succeeded once I removed the parameter files. 

In addition, it seems there is an issue when extracting the version of the software module and the search engine. If I am correct, the software module should be FragPipe (v.21.1) and the search engine should be MSFragger (v4.0). 

Best,
Bart

**Comment by enryH** [comment]
At least during testing the search engine is correctly specified. Did you use the public deployed app?

**Comment by brvpuyve** [comment]
Hi Henry,

I was just checking the MSFragger interface within Proteobench and I did spot one minor issue that we preferably want to resolve. 

More specifically, I noticed that it gives back the same version number for both FragPipe and MSFragger:
 'search_engine': 'MSFragger',
 'search_engine_version': '21.1',
 'software_name': 'FragPipe',
 'software_version': '21.1',

In reality, the version number for MSFragger should be 4.0. 

Sorry that I only spot this error just now.

Bart

**Comment by mlocardpaulet** [comment]
see https://github.com/Proteobot/Results_quant_ion_DDA/pull/193 
it is the pull request that Bart generated.

**Comment by mlocardpaulet** [comment]
> I indeed corrected it. Maybe it's just no present on the deployed version atm?

Do you think that we should try to make a new version now?

**Comment by enryH** [comment]
You can. You will just need to update the Change Log file, then it should be automatically updated.

https://github.com/Proteobench/ProteoBench/blame/main/CHANGELOG.md

**Comment by enryH** [comment]
And for Bart: In the main branch, the parsing is correct, see the [fragger_extracted_params](https://github.com/Proteobench/ProteoBench/blob/main/test/params/fragger_extracted_params.csv) file.

**Comment by mlocardpaulet** [comment]
@enryH I tried locally with the main. It still does not parse well the search_engine_version: 
ProteoBench parsing:
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/62333440-e936-41c2-a096-4dae430db7a6)
fragpipe.workflow:
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/b240cfe1-11b8-432b-9466-8d804d2706f0)
The search engine (MSFragger) version should be 4.0

**Comment by enryH** [comment]
Can you send me the `.workflow` file? (or did you use the one for testing I [linked](https://github.com/Proteobench/ProteoBench/blob/main/test/params/fragpipe.workflow)?)

**Comment by mlocardpaulet** [comment]
I'll send you asap by email.

**Comment by enryH** [comment]
So... As I am developing on Windows, locally Bart's Windows Path is interpreted correctly, but then it produces errors on the UNIX server. So note: We should collect test for all major platforms people run stuff on...
