### ISSUE TITLE
Error when changing `Minimal ion quantifications`

### ISSUE THREAD

**Issue by vedran-kasalica** [Proteobench/ProteoBench#286]
**Describe the bug**
If you scroll the `Minimal ion quantifications` slider 2 times before the page refreshes the following error occurs:

<img width="1219" alt="Screenshot 2024-04-19 at 16 05 51" src="https://github.com/Proteobench/ProteoBench/assets/11068408/315e6622-3c31-4859-9695-4a9b2cea7d46">

This was reproduced locally and on the [server](https://proteobench.cubimed.rub.de/).

**To Reproduce**
1. Go to `DDA Quant Ion Level -BETA-`
2. Click on `Additional parameters`
3. Scroll down to `Minimal ion quantifications (# samples)`
<img width="1238" alt="Screenshot 2024-04-19 at 16 06 09" src="https://github.com/Proteobench/ProteoBench/assets/11068408/2e44ada8-90a7-430b-bcb6-44470e33aa73">

5. Slide the slider back and forth (e.g., from 3 to 4 and then back to 3).
6. The mentioned error should occur

**Expected behavior**
The slider should work without errors.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Google Chrome

**Comment by RobbinBouwmeester** [comment]
Found it! Problem is located here:

#294 

Problem is that this function gets a call with empty all datapoints.

**Comment by wolski** [comment]
Commit 0b4510764fa40f52f741724fab22d3cdeb00f2a3 addresses the error. 
However, I can see that the figures "Log2 Fold Change distributions by species" and "Coefficient of variation distribution in Groups A and B" are not always updated when the sliders are moved.  
The updates work when going from 3 -> 6. However, they are unchanged after moving the slider back to a lower number.

**Comment by mlocardpaulet** [comment]
Hi!
I am not sure that this is related, but I see this error when I use the main locally:
1. Go to DDA Quant Ion Level -BETA-
2. upload a MQ evidence file (unknown from ProteoBench)
3. press parse and bench 
Returns:
no new point in the plot, and `n_prec` = 0 in the table. 
When I move the slide `Minimal ion quantifications (# samples)`, the error is corrected. 

![image](https://github.com/Proteobench/ProteoBench/assets/8386272/24c9c00c-e053-4c99-9f69-12d7dfaaad07)
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/f29bd578-98b8-4046-b84e-f5d8ebc0b9c4)

**Comment by RobbinBouwmeester** [comment]
> Hi! I am not sure that this is related, but I see this error when I use the main locally:
> 
> 1. Go to DDA Quant Ion Level -BETA-
> 2. upload a MQ evidence file (unknown from ProteoBench)
> 3. press parse and bench
>    Returns:
>    no new point in the plot, and `n_prec` = 0 in the table.
>    When I move the slide `Minimal ion quantifications (# samples)`, the error is corrected.
> 
> ![image](https://private-user-images.githubusercontent.com/8386272/328135878-24c9c00c-e053-4c99-9f69-12d7dfaaad07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA0NjMsIm5iZiI6MTcxNTE1MDE2MywicGF0aCI6Ii84Mzg2MjcyLzMyODEzNTg3OC0yNGM5YzAwYy1lMDUzLTRjOTktOWY2OS0xMmQ3ZGZhYWFkMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDYzNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNiYmY3ODY5NTNkODM1N2VlYmEzMjkwZTgwNzQ0MzIyNTZjMjk2YTI0NmU4MTUwNDU1NzI2OWI3MTQyZTk0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TZLHfH8lRF6aRg6Ap_KhYZYFJ9sYeDEnX-gvyqOy6GM) ![image](https://private-user-images.githubusercontent.com/8386272/328135923-f29bd578-98b8-4046-b84e-f5d8ebc0b9c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA0NjMsIm5iZiI6MTcxNTE1MDE2MywicGF0aCI6Ii84Mzg2MjcyLzMyODEzNTkyMy1mMjliZDU3OC05OGI4LTQwNDYtYjg0ZS1mNWQ4ZWJjMGI5YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDYzNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFkMGIzYjcyNDVkOGI0MTAyM2ZkYTcxMjQyZmY0MzQ0NzU4YTMwNTE3MzU1MDYzYjQyMjliOTRiMWQ4NjkxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R4H0PYKVMrrKOaN3OCTvQwrKx7TfaD4XskdGKMTSt7A)

Number of precursors is 0. That is likely part of the issue.

**Comment by mlocardpaulet** [comment]
Well, I should have said that the number of precursors in the evidence table is > 30 K. Sorry. 😅

**Comment by mlocardpaulet** [comment]
Here are the other plots, which are correctly plotted above the main plot:
<img width="958" alt="image" src="https://github.com/Proteobench/ProteoBench/assets/8386272/391d01b8-c89e-435a-ba38-24766f2c6a34">

**Comment by mlocardpaulet** [comment]
Here is a trimmed file that you can use to test if you'd like (Only the top rows of the file that I used to generate the figures)
[evidence_test_20240508.txt.zip](https://github.com/Proteobench/ProteoBench/files/15245714/evidence_test_20240508.txt.zip)

**Comment by mlocardpaulet** [comment]
And I just noticed this message, which appears just after plots are loaded. It is located after the description of the intermediate table in the module page:
<img width="980" alt="image" src="https://github.com/Proteobench/ProteoBench/assets/8386272/b59ff354-ee3d-44ea-ba71-d783249b12b7">

**Comment by RobbinBouwmeester** [comment]
Issue is that for the first submission we do call the part that plots, but not that puts the nr_prec there. I will try to fix this now.

**Comment by RobbinBouwmeester** [comment]
See #296
