### ISSUE TITLE
protein groups parsing for FragPipe

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#301]
I don't think that we parse correctly the ions in FragPipe. 
In the .toml, I see this:
```
[mapper]
"Peptide Sequence" = "Sequence"
Protein = "Proteins"
Charge = "Charge"
```
So do we completely ignore the field `Mapped Proteins`? 
In the combined.tsv table, there are two columns that we need to concatenate to get the protein groups: `Proteins` and Mapped Proteins.  If we only consider the `Proteins`, we only have one accession from the group. This is not what we do for the other pipelines. This clearly overestimates the quantification error because peptide sequences that match several species will be considered in its calculation. 

Here is what I get from the FragPipe output file description (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_iontsv):
```
Protein protein sequence header corresponding to the identified peptide sequence; this will be the selected razor protein if the peptide maps to multiple proteins (in this case, other mapped proteins are listed in the ‘Mapped Proteins’ column)
```

So what we need to do is:
get the value from the column `Proteins`, concatenate with the value of `Mapped Proteins`, and use this as protein group identifyer. @brvpuyve correct me if I am wrong. 
For information, when there are several accessions in `Mapped Proteins`, these are separated by ",".

**Comment by RobbinBouwmeester** [comment]
Can you share the file, that should help us to debug.

**Comment by RobbinBouwmeester** [comment]
Make sure this is still an issue. There two columns with proteins in them.
