### ISSUE TITLE
keep track of ProteoBench version in the parsed parameters of the runs?

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#309]
This is a suggestion. Since we keep uploading files to the module while developing, it would be good to keep track of Proteobench version in the parameters of the runs. This way, when there is a change that can affect the outputs, we can re-run only the subset of output runs that was affected, what do you think?

**Comment by enryH** [comment]
That is definitely an option which is easy to realize. To make this even more meaningful
1. I would switch to identify a version which is in-between releases (using https://setuptools-scm.readthedocs.io/ )
2. Re-running all calculations should be not too expensive. Even if a batch job runs a couple of hours this is good for our setup.

**Comment by RobbinBouwmeester** [comment]
Done in #325
