### ISSUE TITLE
search results accesible for download?

### ISSUE THREAD

**Issue by adder** [Proteobench/ProteoBench#316]
Hey,

This looks like a very interesting and useful project! Thanks for developing this.

I was wondering if the upload search results showcased in the benchmark are available for download?
This would be very useful  to test and benchmark different post processing steps. (eg. differential expression analysis)

thanks!

**Comment by mlocardpaulet** [comment]
Hi, thank you for your message!
Yes, we plan to make all the data (files uploaded to ProteoBench and intermediate parsed tables) publicly available. It is not yet the case for practical reasons but we should soon provide a way to access them.

**Comment by julianu** [comment]
Created a PR addressing this #369

**Comment by mlocardpaulet** [comment]
It is now possible to access the data that we store (uploaded files -- parameter and ion quantification -- and the intermediate table that is generated). There should be an area for this in the bottom of each module. If it is not accessible yet it will be in a new version soon.
