### ISSUE TITLE
Parameter parsing not compatible with MQ 2.6.2.0

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#338]
**Describe the bug**
Parameter parsing does not seem to be set up for MQ 2.6.2.0

**To Reproduce**
1. Upload the MQ evidence file from a version 2.6.2.0
2. Click on 'PARSE AND BENCH' -> it works nicely
3. Scroll down to 'Add Results to online repository' and upload the corresponding mqpar.xml (it was actually renamed 'mqpar_mq2.6.2.0_1mc_MBR.xml')
4. See error:
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/fdd51c20-5c0b-46c2-9679-1bcb76b1588c">

**Expected behavior**
The parsed parameter should be printed.

**Desktop (please complete the following information):**
 - OS: macOS 14.5 (23F79)
 - Browser Chrome
 - Version 127.0.6533.89

**Comment by RobbinBouwmeester** [comment]
Should be fixed in the latest release v0.3.0
