### ISSUE TITLE
issue with MQ parsing of modifications

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#339]
**Describe the bug**
The intermediate file contains peptidoforms with "MO[M]" for methionine oxydation. It should be "M[ox]" or similar.

**To Reproduce**
1. upload MQ evidence file from version 2.5.2.0 or above
2. PARSE AND BENCH
3. the peptidoforms do not seem correct
<img width="461" alt="image" src="https://github.com/user-attachments/assets/f62b7099-f0b1-4a36-bfc2-e37e8be7dbda">

**Expected behavior**
methionine oxydation should be "M[ox]", and I did not check other PTMs

**Comment by RobbinBouwmeester** [comment]
Should be fixed in the latest release v0.3.0
