### ISSUE TITLE
Full support all software ion module

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#346]
Not all software are supported for the DDA quant ion module. We need to test what is fully supported and what might still need changes.

**Comment by scaramonche** [comment]
I tested both parsing of sample input files and parameters parsing for MaxQuant, FragPipe, AlphaPept, i2MassChroQ, Sage and it works fine. I have to double check Proline. 
Some notes:
- Change Proline to Proline Studio 
- Check if we can have multiple input column names mapping to the same output column names, which might be needed for Proline, where col names might change. 
- Check parsing of modifications for Sage

**Comment by scaramonche** [comment]
What about Wombat?

**Comment by mlocardpaulet** [comment]
see https://github.com/Proteobench/ProteoBench/issues/354 for Proline support
