### ISSUE TITLE
Peptidoform module

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#347]
We need to figure out what is currently supported, what input files we need exactly, and what we can add.

**Comment by mlocardpaulet** [comment]
I think that in the peptidoform module we could add WOMBAT-P data. Maybe @veitveit could generate some for us?
And maybe Proteome Discoverer has an output at peptidoform level that we could use.

**Comment by mlocardpaulet** [comment]
I think that we could also use some MQ outputs from the same searches as the ones done for the ion module. Not the evidence.txt but there is another text export with peptides (I think). 
Should I send you some?

**Comment by mlocardpaulet** [comment]
It will be super great to have the WOMBAT-P runs because they should already cover several pipelines ❤️
