### ISSUE TITLE
no change in the proteobot pull request generated when uploading public data on server (MQ)

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#350]
**Describe the bug**
There is no change logged in the pr that is sent through proteobot when I make MQ search results public. Except this, all work very well.
See https://github.com/Proteobot/Results_quant_ion_DDA/pull/217 as an example.
The parameters were well parsed and printed when I pressed "I really want to upload it".

I am using the server: Using proteobench version: 0.3.3.dev0+g9a9ce1d.d20240829

**Comment by RobbinBouwmeester** [comment]
Fixed #351
