### ISSUE TITLE
plot disappears when selecting a point to highlight

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#353]
**Describe the bug**
When I select a point to highlight (in the table below the plot), everything bellow the "input files" box disappears.
Using proteobench version: 0.3.4.dev0+g0848925.d20240902

**Comment by mlocardpaulet** [comment]
this seems to be linked to https://github.com/Proteobench/ProteoBench/issues/352

**Comment by RobbinBouwmeester** [comment]
Resolved in #405
