### ISSUE TITLE
change point information -> use "submission comment" instead of "comment" on reference points (publicly available)

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#355]
When we publicly upload a run, we save the comment in the "additional information" field and in the "submission comment" field. 
In the end, the first one is chosen to be visualised when we hover on the plot. 
Isn't it weird? I would select the second comment (the one that we make at public submission). In my mind the first one was more for local visualisation. No?

Either way it has to be clear in the description. Currently, there are inconsistency in the comments (because I did not care about the first "additional information" comment).

**Comment by mlocardpaulet** [comment]
To be honest, I think that we should remove the "additional information" altogether. I think that it is confusing. People think that they need to fill it out.

**Comment by scaramonche** [comment]
see #382

**Comment by scaramonche** [comment]
Working on the second point in #384.
