### ISSUE TITLE
Datapoints plot / table does not load/reload

### ISSUE THREAD

**Issue by julianu** [Proteobench/ProteoBench#359]
On the local version, the plot of already uploaded data does not plot on (same) cases of opening the "DDA quant ion" module. When selecting to highlight a datapoint, the page tries to reload and the plots and table are not rendered anymore.

**To Reproduce**
1. Open module
2. Either the plot shows or not, hard-reloading the page usually renders the plot
3. Select a datapoint to highlight in the plot -> reloading does not render the plot

**Expected behavior**
All plots and tables should be shown each time

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FireFox
 - ProteoBench version [e.g. 0.3.4-dev]

**Comment by julianu** [comment]
this is related to #353 (which I just saw now)

**Comment by OlivierLangella** [comment]
Hello, I've the same behaviour for the DDA quant ion module : 
datable and scatterplot does not update if the "Minimal ion quantifications (# samples)" is modified

Any interaction in the scatterplot leads to the empty input file form.

Indeed, related to #353

**Comment by RobbinBouwmeester** [comment]
Resolved in #405
