### ISSUE TITLE
Calculate coefficient of variation and store information about missing.

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#40]

**Comment by viikiid** [comment]
add also to intermediate files

**Comment by wolski** [comment]
How about adding mean, 50% 75%, and 95% quantiles of the CVs for each group (A, B) to the datapoint?

**Comment by mlocardpaulet** [comment]
I tried it out and I see that the "0" are not removed anymore. They should be replaced by "NA"

**Comment by RobbinBouwmeester** [comment]
@wolski this is done?

**Comment by wolski** [comment]
I added the median, Q75, and Q90 of CV to the datapoint result in commit 9632b76454ab45430af181840a5098090d29b8a9.

How do we visualize it?

**Comment by wolski** [comment]
I think it is done. Visualizing CVs can be a new issue.
