### ISSUE TITLE
Improve readability of metric plot

### ISSUE THREAD

**Issue by Cajac102** [Proteobench/ProteoBench#400]
It is currently hard to understand which parameters change between the benchmark runs. It takes a bit of hovering, and sometimes  two points have the exact same hover text, making it impossible to see what changed.  

Suggestions for readability improvements:

1. Add a legend to show which colors correspond to which search engines
2. Make it possible to show specific parameters as point labels in the plot (e.g. show if MBR was activated). Will probably lead to crowded plots and overlapping labels, but would help a lot with investigating the results.
3. Compare two points: Make it possible to select two points to show the differences directly.

Point 3 is probably harder to implement, and might be something for after we switch to a new web framework.

**Comment by RobbinBouwmeester** [comment]
Resolved in #405
