### ISSUE TITLE
new support for i2MassChroQ using Sage instead of X!Tandem

### ISSUE THREAD

**Issue by OlivierLangella** [Proteobench/ProteoBench#417]
**Is your feature request related to a problem? Please describe.**
no problem, many thanks for the new web user interface ! it is well done.
i2MassChroQ is already supported, but I had to add new parameters in the metadata specific to the Sage identification engine.
Those new tags in the metadata csv file are not taken into account yet.

**Describe the solution you'd like**
So I've reported the main Sage parameters in the metadata file. The new parameters dedicated to sage are present in this file : 
```
Module_2_DDA_quantification/search_results/i2MassChroQ/i2m_and_sage/Project parameters.tsv
```
in the dedicated cloud.

**Additional context**
The result is interesting and I would like to publish it
![image](https://github.com/user-attachments/assets/32bd7ad8-9b61-4a90-8680-6b7998e42f20)
with relevant metadata

Thanks a lot !
Olivier

**Comment by mlocardpaulet** [comment]
thanks, we should definitely make this work.
Is it normal that there are no values in the FDR fields?

**Comment by OlivierLangella** [comment]
Hello @mlocardpaulet  !
oh no, that's a bug... thanks I'll check this

**Comment by OlivierLangella** [comment]
I've checked the file, here are the FDR fields reported : 
```
i2m_psm_fdr_threshold_target	0.006
peptide_fdr	0.008561447245
protein_fdr	0.009234643907
psm_fdr	0.005999419143
```
is this the right fields or is there an other field ?
https://github.com/Proteobench/ProteoBench/blob/369dd02231560e3d5be7c624d06ebf3bb45b6484/proteobench/io/params/i2masschroq.py#L33

**Comment by OlivierLangella** [comment]
Hello @mlocardpaulet , is this field OK or am I missing something ?
Thank you
Olivier

**Comment by mlocardpaulet** [comment]
yes, these are OK :). It is just that these are empty in the parameter file in the cloud.

**Comment by OlivierLangella** [comment]
Oh that is weird, when I download the file in the cloud, I get this :
```
langella@piccolo:~/Téléchargements$ cat /tmp/Project\ parameters.tsv  | grep fdr
i2m_psm_fdr_threshold_target	0.006
peptide_fdr	0.008561447245
protein_fdr	0.009234643907
psm_fdr	0.005999419143
```
in the directory "i2m_and_sage". Tell me if it is the case for you, otherwise I'll just put the file elsewhere.

Thanks again
Olivier

**Comment by mlocardpaulet** [comment]
> Oh that is weird, when I download the file in the cloud, I get this :
> 
> ```
> langella@piccolo:~/Téléchargements$ cat /tmp/Project\ parameters.tsv  | grep fdr
> i2m_psm_fdr_threshold_target	0.006
> peptide_fdr	0.008561447245
> protein_fdr	0.009234643907
> psm_fdr	0.005999419143
> ```
> 
> in the directory "i2m_and_sage". Tell me if it is the case for you, otherwise I'll just put the file elsewhere.
> 
> Thanks again Olivier

Oh no! You are right. Sorry. I don't know what I did to not see these 🤦 
It looks all good. Sorry for the wasted time.

**Comment by mlocardpaulet** [comment]
@OlivierLangella , sorry this takes some time. In the meantime, if you want to submit points from i2MassChroQ that use Sage, you can indicate the parameters that you find interesting in the comment field when you publicly submit. This will then be visible on hovering and in the table below the plot of the module. 
I hope that this help

**Comment by RobbinBouwmeester** [comment]
Resolved.

**Comment by mlocardpaulet** [comment]
Hey @RobbinBouwmeester, you closed this issue. Is it really done? I don't think so. Or does it mean that you don't want to parse the Sage-specific parameters? Or that we'll do it later.

**Comment by OlivierLangella** [comment]
Hello @RobbinBouwmeester, like @mlocardpaulet I am wondering if sage results are taken into account. I do not see the results in the public interface, nor code modification in the parser to handle it. Is it abandoned ?

**Comment by mlocardpaulet** [comment]
Closing was an error. I reopen, but it is not a priority right now.

**Comment by mlocardpaulet** [comment]
Sorry, I did not realise that it completely prevented public upload. I will start a PR.

**Comment by mlocardpaulet** [comment]
@OlivierLangella I struggle to find the information of enzyme cleavage in the parameters of sage. I see this:
```sage_database_enzyme_restrict	P```
Is is always trypsin by default? Is there another field that we should parse?
