### ISSUE TITLE
ProteoBenchFASTA download link not working

### ISSUE THREAD

**Issue by Cajac102** [Proteobench/ProteoBench#418]
In the documentation for the DDA module (https://proteobench.readthedocs.io/en/latest/available-modules/2-DDA-Quantification-ion-level/#how-to-use), the link to download the Fasta is broken (Error: "The page you requested does not exist or may have been removed")

**Comment by mlocardpaulet** [comment]
thanks for seeing this! Maybe this can be fixed with the issue #403 ?

**Comment by rodvrees** [comment]
Same happens on https://proteobench.readthedocs.io/en/latest/available-modules/4-DIA-Quantification/

**Comment by GeorgWa** [comment]
Hi, are there any updates on this? :) 
I would like to run some benchmarks but can't access the fasta.

**Comment by rodvrees** [comment]
Hi Georg, pending a fix, here's the fasta:
[ProteoBenchFASTA_DDAQuantification.txt](https://github.com/user-attachments/files/17618596/ProteoBenchFASTA_DDAQuantification.txt)


GitHub doesnt allow files with .fasta extension to be added here, so had to change it to .txt. So best to rename the file name again.

**Comment by GeorgWa** [comment]
Thanks! appreciate it
