### ISSUE TITLE
Support proline input directly instead of wombat-proline

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#42]

**Comment by RobbinBouwmeester** [comment]
Could not find David in the assignee list, I think he would be the main responsible.

**Comment by veitveit** [comment]
Should be rather easy though as Proline provides one comprehensive excel table with different sheets on PSM, peptide and protein level

**Comment by veitveit** [comment]
Guys, I did that one already in the pull request with the new documentation #67 . But please test it at I did not do that yet.

**Comment by mlocardpaulet** [comment]
Great. But I think that there may be some stuff to deal with for Proline direct export:
1. there is the option of exporting an excel file, but by default it does not contain the "quantified ions" sheet
2. it is possible to export a tsv file (maybe we should only accept this imput), but if we do that, the column header for charge state is `master_quant_peptide_ion_charge`.

**Comment by veitveit** [comment]
OK, that needs to be corrected. Can you try? 

I probably use the wrong column then for the quantification then as the best PSM is definitely not the right one. 

In WOMBAT-P, we process the Proline output further and I will have to check which columns we use. The results tell that it is the right one though.

**Comment by mlocardpaulet** [comment]
Sure, I will take care of the direct outputs from Proline - correct the current import parameters. :)
