### ISSUE TITLE
Local usage requires secrets.toml file, can be empty

### ISSUE THREAD

**Issue by bfurtwa** [Proteobench/ProteoBench#421]
To avoid the error:
`FileNotFoundError: No secrets found. Valid paths for a secrets.toml file or secret directories are: C:\Users\...\.streamlit\secrets.toml, C:\Users\...\proteobench\ProteoBench\webinterface\.streamlit\secrets.toml`

place an empty `secrets.toml` file into the directory

**Comment by RobbinBouwmeester** [comment]
Fixed in #476
