### ISSUE TITLE
add a way to inspect submitted files for public submission approval

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#423]
Currently, when there is a new PR (with a new data point) in proteobot, we can see the changes in the parsed settings and results, but we do not see the files uploaded by the user (result files and parameter files). 
I think that it should be possible, to have an inspection a bit more thorough when we accept the PR. 
What do you think? Would this be possible?

**Comment by RobbinBouwmeester** [comment]
Works in #487
