### ISSUE TITLE
value does not print for alphapept points when selecting MBR

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#424]
**Describe the bug**
the value ("False", according to the value I see on hovering) does not print on the alphapept points when we select the value "enable_match_between_runs" in the field "Select label to plot". I did it in the DDA module, in the first tab ("Public benchmark runs"), see screenshot below:

<img width="603" alt="image" src="https://github.com/user-attachments/assets/e8eb772c-c26a-4e44-86dd-510c76baee76">

The value is printed for all other search software, and for the alphapept points with MBR. 

Except that, this is a really cool feature to print the parameter values :)

**Comment by Cajac102** [comment]
Nice catch, I band-aided it with a temporary fix. The issue is that the values in the fields are not homogenous, so sometimes MBR is a boolean instead of a string and stuff goes haywire. As soon as #380 is fixed, everything should work :)
