### ISSUE TITLE
Parse fragpipe params differently for DIA and DDA

### ISSUE THREAD

**Issue by rodvrees** [Proteobench/ProteoBench#429]
We have distinct parameters that need to be parsed from the fragpipe.workflow file for DDA and DIA data analysis. At the moment, no distinction is made and DDA params are being parsed for both DDA and DIA modules.

**Comment by rodvrees** [comment]
Same goes for MaxQuant/MaxDIA

**Comment by RobbinBouwmeester** [comment]
@rodvrees, is this still an issue?

**Comment by rodvrees** [comment]
Yes, but should be easily fixed now after the refactoring
