### ISSUE TITLE
Store intermediate files on server/github

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#43]

**Comment by RobbinBouwmeester** [comment]
@mlocardpaulet, it was decided to go with the solution from Julian?

**Comment by mlocardpaulet** [comment]
Yep. Hopefully he will find a solution quickly (on his server or some others nearby)

**Comment by RobbinBouwmeester** [comment]
Done in #140, add the following to the secrets.toml:
```
[storage]
dir = "C:/temp/"
```
