### ISSUE TITLE
Datapoint metric is called 'median_abs_epsilon' but is actually mean

### ISSUE THREAD

**Issue by rodvrees** [Proteobench/ProteoBench#436]
Median_abs_epsilon is calculated here: 

https://github.com/Proteobench/ProteoBench/blob/8ed5b5ad9588b5b8b10c3b0cfd9ec284be43a59a/proteobench/datapoint/quant_datapoint.py#L124-L127

So is actually mean. Since the comment suggests that the metric should be unaffected by outliers, should we actually calculate the median instead or just rename the metric to mean_absolute_median. In the scatter plot, in which this value is plotted on the x-axis, the label correctly says it's the mean absolute error.

**Comment by mlocardpaulet** [comment]
This is a really good catch. Thanks a lot. 
My opinion: we fix the error and plot the median value in the figure, and...
let's calculate and provide both median and mean in the intermediate result table. This way:
- users who download the intermediate data can plot the one they want
- we can have a figure in the paper to compare median and mean, and justify why we pick the median to reduce the impact of outliers in the main module figure

What do you think?

**Comment by rodvrees** [comment]
As discussed, mean vs median for the tools comparison, let me know if you want to see anything else compared between the two:

![Meanvsmedian](https://github.com/user-attachments/assets/43df2c1e-d65a-46cd-8588-db8ca1f0fc47)

**Comment by RobbinBouwmeester** [comment]
Could you do the DDA ion quant?

**Comment by rodvrees** [comment]
I can't retroactively recalculate metrics for the submitted points without having the data myself, but I'll download some DDA search results from the clouds and run them through both, is that okay?

**Comment by rodvrees** [comment]
Used the data from the 'standard_parameters' DDA runs from the cloud, and plotted what the metrics would look like in both scenarios (was a bit lazy, color sheme is different between the two plots): 

![Meanvsmedian_DDA](https://github.com/user-attachments/assets/faff5cc8-4c20-4060-b761-544b41d543c2)

**Comment by wolski** [comment]
I recall the plan was to use the [median absolute deviation](https://en.wikipedia.org/wiki/Median_absolute_deviation).

**Comment by RobbinBouwmeester** [comment]
You deserve to be way more lazy, it is your holiday after all...

**Comment by wolski** [comment]
1+ for the median absolute deviation (mad) https://en.wikipedia.org/wiki/Median_absolute_deviation, since more robust to outliers, although it means we need to recompute the points. Let me know if I can help with it.

**Comment by mlocardpaulet** [comment]
To be honest, I don't feel strongly about it. I see interest in both metrics. But since there is a discussion about it, I think that we should recompute the points.
If I am not mistaken, @rodvrees changed the script so that it now calculates mean and median and stores it. This way, we can easily check the difference afterwards if we want to.

The question is: how do we recompute and when? Do we wait for @juliaS92's work on automatising recomputing for all points?

**Comment by mlocardpaulet** [comment]
Looking into Spectronaut outputs with @brvpuyve, we noticed that there are many very low intensity values (<1000). These have a huge impact on the result if we use the mean. 
According to my calculation, on these data (dataset in the cloud), here would be the x-axis values:
mean = 0.7578774
median = 0.203918

**Comment by mlocardpaulet** [comment]
... So seeing this I think that I would be in favour of using the median. Mostly to make our life easier. 
What do you all think?

**Comment by wolski** [comment]
> Looking into Spectronaut outputs with @brvpuyve, we noticed that there are many very low intensity values (<1000). These have a huge impact on the result if we use the mean. According to my calculation, on these data (dataset in the cloud), here would be the x-axis values: mean = 0.7578774 median = 0.203918

The difference is vast. Indeed an argument to use the median, as the main score, which shows, that the bulk of the data is of high quality.
Although, the mean hints at a problem. I assume that all <1000 features have a significant Qvalue < 0.01?

**Comment by rodvrees** [comment]
New branch https://github.com/Proteobench/ProteoBench/tree/mean_median_plot includes feature to choose between plotting mean and median. Seems to work in terms of what's happening, but cannot be properly tested until we can recalculate the median errors for already submitted points

**Comment by rodvrees** [comment]
Updated PR: #489

**Comment by RobbinBouwmeester** [comment]
Fixed in #498
