### ISSUE TITLE
Validate search parameters

### ISSUE THREAD

**Issue by viikiid** [Proteobench/ProteoBench#44]

**Comment by RobbinBouwmeester** [comment]
Could we write a small part about what valid search parameters are in this issue?

**Comment by viikiid** [comment]
The idea was to validate the additional parameters, e.g., whether they are in a meaningful range 
FDR: between 0 and 1
Precursor mass tolerance: if ppm: 0-100; if Da: 0-300 (to allow for open searches)
Fragment mass tolerance: if ppm: 0-100; if Da: 0-3
Max missed cleavages: 0 - 7
Modifs: parsing and format needs to be defined first
charge states: 1-10
Max modifs per peptide: 0-10
min pep length: 0-12 (or 1-12)
max pep length: 0 (unchecked?) - 80
