### ISSUE TITLE
file naming and organisation in `io/params/parsing/io_parse_settings`

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#442]
I think that we should be more precise in the naming of the toml files for opening/parsing the input files of the different modules, specially if these are all in the same folder. 
I say that because the different tools have several outputs, and it is not the same output table that will be used if we want to run the DDA peptidoform, DDA precursor ion or DIA module. It is at least the case for Proline, and I think for i2MassChroQ. I also see that this is the case for FragPipe that already has a fragpipe.toml and fragpipe_DIA.toml.
I think that it would be better to be very systematic: `fragpipe_DDA_ion.toml`, `fragpipe_DDA_peptidoform.toml`, `fragpipe_DIA_ion.toml`...
Maybe there is an even better way to handle this. 

I know that in some cases, the toml will be exactly the same for several modules. But wouldn't it be cleaner to still have several toml? The idea is to make it simpler for people who want to add tools. Of course this is very open to discussion.

**Comment by rodvrees** [comment]
Hi Marie,

In trying to implement the diaPASEF ion quant module that we'll use the newly generated diaPASEF for, I quickly found that indeed, the current way the repo is structured is not very friendly towards adding new modules, especially modules that are very similar but need slight changes. So in the PR I'm drafting for this new module I have (probably gone a bit overboard) and restructured quite a bit. Once I'm done I will let you know, and then we should discuss it a bit more. I might draft the new diaPASEF module again in another PR without the restructuring, so we can take a longer time to discuss the refactoring outside the implementation of the diaPASEF module.

**Comment by mlocardpaulet** [comment]
I love this! Thank you so much. 
Please let me know if I can help in any way.

**Comment by rodvrees** [comment]
Organization is restructured after refactoring (#452). Each module now has its own folder of tomls. There are improvements to be made, because the tomls themselves contain a lot of information that can be generalized, but this can be made into a new issue.
