### ISSUE TITLE
Link to fasta file for DDA module throwing 404 error

### ISSUE THREAD

**Issue by temaia** [Proteobench/ProteoBench#443]
Hi, just to let you know the link (https://proteobench.cubimed.rub.de/datasets/fasta/datasets/fasta/ProteoBenchFASTA_DDAQuantification.zip) to get this fasta file is not working.

**Comment by mlocardpaulet** [comment]
Thanks a lot for letting us know. 
I think that this issue already exists: #418. You can go there and find a temporary link to the fasta file. Hope it helps.
