### ISSUE TITLE
add raw file names next to link to PXD

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#449]
Currently in the doc. we have this:
```
The files can be downloaded from the proteomeXchange repository PXD028735 (https://www.ebi.ac.uk/pride/archive/projects/PXD028735) or you can download them from the ProteoBench server here: https://proteobench.cubimed.rub.de/datasets/raw_files/DDA/
```
The link to proteomeXchange is not enough. We need to add the names of the raw files for users to find them.

**Comment by wolski** [comment]
The previous version of Proteobench had the download links to the raw files on the main page.

These links are missing at the moment.
The new one needs these links to get everyone started.



We should

**Comment by mlocardpaulet** [comment]
what do you mean by "the main page"? We discussed in the past that it would be cleaner to have the download links with the complete explication of the module and how to use it: in the documentation. I think that it is good. 
Specially because in the module page, in the tab `Submit new data`, there is this text:
<img width="854" alt="image" src="https://github.com/user-attachments/assets/19842448-5c25-4265-ad17-848a8d7792cf">

What I meant when I created this issue was that in the documentation, the link to the PRIDE repo. is not enough. We need to link to individual files, or at least indicate their names. 
Does this make sense?

We don't want to duplicate information and have these links in the module streamlit page and in the documentation.

**Comment by wolski** [comment]
I wasn't aware of this change. Makes sanse to have the information in one place.

However, the links "How to use" and "Data Set" are 'broken' in the DIANN module at the moment.

<img width="677" alt="image" src="https://github.com/user-attachments/assets/7e38d357-d262-4c1f-827d-5106d0f4361c">

What are the correct links? I can try to update them.

**Comment by wolski** [comment]
Also, the link here:
https://proteobench.readthedocs.io/en/stable/available-modules/4-DIA-Quantification/
to the fasta is not working.
<img width="677" alt="image" src="https://github.com/user-attachments/assets/e167c531-55a1-413e-bda2-8abcbceac656">

**Comment by mlocardpaulet** [comment]
> I just wanted to suggest something similar, when looking into it. I think it would be great, if there was a list of the actual direct links to the ftp servers for each raw file like so: https://ftp.pride.ebi.ac.uk/pride/data/archive/2022/02/PXD028735/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.raw Then nobody needs to read any description of which files to download and which ones not.

Yes! Absolutely. Actually, it is the way it was in the past.
