### ISSUE TITLE
Make required software settings more transparent and easily accessible

### ISSUE THREAD

**Issue by JuliaS92** [Proteobench/ProteoBench#456]
**Is your feature request related to a problem? Please describe.**
When running the analysis for a new datapoint make it as easy as possible to make the correct parameter selections required for the processing to work. I can see several ways to improve this, as one currenlty needs to follow the links to the docs and then find and read the right sections (shouldn't be a hurdle for anybody who goes there on purpose, but still takes away time).

**Describe the solution you'd like**
- When selecting the software in proteobench, display the corresponding text from https://proteobench.readthedocs.io/en/latest/available-modules/2-DDA-Quantification-ion-level/#important-tool-specific-settings in the app
- In the documentation include sample setting files or link to an example run for the respective software
- If a tool can be run from the command line spell out the cmd args that are required for a valid run

**Comment by mlocardpaulet** [comment]
Agreed. I think that we can definitely improve the documentation with the 2 last points that you made. 
For your first point: 
just to make sure that I understand, if one selects "ProlineStudio", you would print ".xlsx" in the field of the "Software result file"? It makes sense. I still think that users will always need to have a look at the documentation anyway before they make their first submission.

**Comment by JuliaS92** [comment]
Not quite, I mean actually display the information form the documentation between the dropdown and the fileupload, so they don't need to explicitly find the information in the docs.

**Comment by mlocardpaulet** [comment]
Yes, well, it was like this before. And we decided to move everything to documentation to avoid duplicating information (it also makes it harder to keep it up to date without mistakes). I would be in favour to keep this strategy for now:
as little information as possible in the actual application, everything in the documentation. 
But we could completely discuss this again in a future in-person meeting.

**Comment by RobbinBouwmeester** [comment]
Closing this for now, can reopen if the issue needs to be discussed again
