### ISSUE TITLE
BUG: missing information in the file `result_performance.csv` downloaded for `FragPipe__20240903_121541`

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#465]
**Describe the bug**
If I download the file `result_performance.csv` from the DDA module for the point `FragPipe__20240903_121541`, I only have the rows of the precursors with `nr_observed` = 6. 

There should be all the rows (with `nr_observed` from 1 to 6). 

I have not checked yet if the same thing happens with other points or modules.

**Comment by RobbinBouwmeester** [comment]
There should be information in other columns. Specific ones get parsed out though at time of plotting.

**Comment by RobbinBouwmeester** [comment]
Ok, had a look, what is the link to the file you used?

**Comment by mlocardpaulet** [comment]
Not sure I understand what link you are talking about. I am talking of the intermediate table for the data point 7f1e8060ed9a177397cf192659fc1b49a94a7925
