### ISSUE TITLE
issue with ProlineStudio precursor ions parsing

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#473]
**Describe the bug**
In ProlineStudio exports, the table contains multiple rows for the same precursor ions if they match to several proteins. For example this precursor (AALGVLR|Z=2):
![image](https://github.com/user-attachments/assets/86bb7053-2b42-4897-945f-2c476710f6ec)
I think that we dealt with this in the past, thanks to @RobbinBouwmeester, but when I try now, I have two rows in the intermediate table: one for the ecoli protein and one for the human protein. They are both considered unique, so the epsilons are computed for both. This is wrong.

**Comment by mlocardpaulet** [comment]
@RobbinBouwmeester do you remember writing a script to combine these rows in the past? I thought you did but I cannot find this in the code. Or am I imagining it? We need a fix.

**Comment by mlocardpaulet** [comment]
So you know, there is a PR in progress for ProlineStudio compatibility: https://github.com/Proteobench/ProteoBench/pull/471

**Comment by mlocardpaulet** [comment]
I found it, we saw and discussed this issue in the past here: 
https://github.com/Proteobench/ProteoBench/issues/251

**Comment by mlocardpaulet** [comment]
and it was fixed (I think) here: 
https://github.com/Proteobench/ProteoBench/pull/252

**Comment by mlocardpaulet** [comment]
I am happy to put it back, but I am not sure where. I don't want to mess up the code. 
I have a meeting with ProlineStudio developers Monday afternoon, I can do it over the weekend.

**Comment by mlocardpaulet** [comment]
should be fixed here: https://github.com/Proteobench/ProteoBench/pull/471

**Comment by RobbinBouwmeester** [comment]
Merged :)
