### ISSUE TITLE
How to handle X!Tandem hidden parameters that have an impact on final results?

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#477]
**Problem**
Some search engine parameters are "hidden", they are used by default and not necessary reported in the parameter files. This is the case for X!Tandem, that uses some modifications by default, and these are not reported in the software tool parameter file (ProlineStudio or i2MassChroQ). 
This contributes to the fact that the i2MassChroQ point `2MassChroQ__20240904_071654` is so high : it contains a lot of `A[MOD:00394]`, but this is not visible at all in the parameters reported on the page with the plot. 

We really need to do something about this.

**Possible solutions**
1. we could check that all the modifications in the intermediate file are reported in the parsed parameters. If not, we can print an error message and stop public upload. 
2. we can see with developers if there is a way to find this information in their parameter files?

**Comment by RobbinBouwmeester** [comment]
Do you have the parameter file somewhere?

**Comment by mlocardpaulet** [comment]
> Do you have the parameter file somewhere?

which one? The thing is: this parameter is in the X!Tandem parameter file. It does not appear anywhere currently in the ProlineStudio or the i2MassChroQ parameter file. We need to discuss this with the developers if we want it to be added. 
And I have no idea how many other hidden parameters are tool-specific. Maybe @veitveit have some experience with this, and would have some advices?

**Comment by mlocardpaulet** [comment]
While we are working on this issue,  maybe we should remove the data point `i2MassChroQ__20240904_071654`?

**Comment by RobbinBouwmeester** [comment]
> > Do you have the parameter file somewhere?
> 
> which one? The thing is: this parameter is in the X!Tandem parameter file. It does not appear anywhere currently in the ProlineStudio or the i2MassChroQ parameter file. We need to discuss this with the developers if we want it to be added. And I have no idea how many other hidden parameters are tool-specific. Maybe @veitveit have some experience with this, and would have some advices?

Of both. I assume running X!Tandem first should also provide you with that file?

> While we are working on this issue, maybe we should remove the data point `i2MassChroQ__20240904_071654`?

Personally I see no reason to do that. There are other datapoints that are currently missing parameters. Unless we also remove those, I would keep it. Also, if acetylation of the N-terminal is the reason, all the better it was included and that is reflected by the improved sensitivity.

**Comment by RobbinBouwmeester** [comment]
I know we removed this feature, but I would be very much in favor of having user input fields for the cases where a straightforward parameter file cannot be provided.

This might also partly resolve the custom file format submission thing. If parameters are (partly) user submitted we should maybe just run extra checks before approving a point.

**Comment by OlivierLangella** [comment]
Hi everyone,
In fact, I've reported those parameters in the file provided in the cloud :
i2MassChroQ/20241121_proteobench_1fdr_2mc/Project\ parameters.tsv
(the kind of file that was submitted along with the proteobench export table)

```
protein, quick acetyl	yes
protein, quick pyrolidone	yes
```
| tandem parameter | online documentation |
| -------------------| ------------- |
| protein, quick acetyl | https://www.thegpm.org/TANDEM/api/pqa.html |
| protein, quick pyrolidone | https://www.thegpm.org/TANDEM/api/pqp.html |

I think it is fair to allow it as long as this is well documented and displayed.

I hope there is no hidden parameters in what I've submitted, I've tried to report as much as possible all tricky parameters.

Concerning the sage results, this is also reported by a line :
```
sage_database_variable_mods	M:15.994915 ^E:-18.010565 ^Q:-17.026548
```
(the equivalent of the quick pyrolidone seach, this makes me think it would be interesting to also look for acetylation)

**Comment by mlocardpaulet** [comment]
Thanks for the information. 
I did not mean that we should permanently remove the points. But right know it really looks like the only variable modification allowed is oxidation of M. This is misleading. Do you think that we could add acetyl and pyrolidone when we see "quick acetyl yes" and "quick pyrolidone yes" in the parameter file? This would fix it. 
I also think that it would not hurt to check that we find the same modifications in the results as the ones set up in the parameters.

**Comment by OlivierLangella** [comment]
Hi @mlocardpaulet !
yes, I think it is safe to add acetyl and pyrolidone if we have "quick acetyl yes" and "quick pyrolidone yes" in the parameter file.
If it is possible to check for this in the resuls, yes also, it would not hurt.

**Comment by mlocardpaulet** [comment]
> Hi @mlocardpaulet ! yes, I think it is safe to add acetyl and pyrolidone if we have "quick acetyl yes" and "quick pyrolidone yes" in the parameter file. If it is possible to check for this in the resuls, yes also, it would not hurt.

Great! I will have a look at how to do that!

**Comment by RobbinBouwmeester** [comment]
> Thanks for the information. I did not mean that we should permanently remove the points. But right know it really looks like the only variable modification allowed is oxidation of M. This is misleading. Do you think that we could add acetyl and pyrolidone when we see "quick acetyl yes" and "quick pyrolidone yes" in the parameter file? This would fix it. I also think that it would not hurt to check that we find the same modifications in the results as the ones set up in the parameters.

This does mean we need to scan the parameter file for anything that says "quick [] yes", otherwise we will have the same issues for other modifications.

**Comment by mlocardpaulet** [comment]
I think that there are only these two options. But I will check. 
And do you have another options?

**Comment by OlivierLangella** [comment]
> This does mean we need to scan the parameter file for anything that says "quick [] yes", otherwise we will have the same issues for other modifications.
> 
> I am really not in favor of hardcoding in specific modifications.

That's a good solution. 

> I think that there are only these two options. But I will check.
> And do you have another options?

I confirm there is only those 2 specific modifications that are hard coded by X!Tandem.

**Comment by RobbinBouwmeester** [comment]
> I think that there are only these two options. But I will check. And do you have another solution in mind?

Yes, this:

> I know we removed this feature, but I would be very much in favor of having user input fields for the cases where a straightforward parameter file cannot be provided. This might also partly resolve the custom file format submission thing. If parameters are (partly) user submitted we should maybe just run extra checks before approving a point.

**Comment by mlocardpaulet** [comment]
I am not against it. But this really needs to be discussed and well thougth of. Maybe @RobbinBouwmeester  you can open a discussion about it?
Also, **it would not change the issue here** because users may bot be aware that these modifications are searched since it is completely hidden. So I like the idea of changing the parameter parsing to add these two mod. 
The information would probably still be misleading with manual entry of the parameters. 
So I think that we need to have a check that compares modifications in the results and modifications in the parameters (whatever the way we enter parameters: manually or with automatic parsing).
