### ISSUE TITLE
Check duplicate workflows and results

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#49]

**Comment by MartinRykaer** [comment]
Would comparing hash values work for this?

**Comment by MartinRykaer** [comment]
I wrote something that I think would work, but I am unsure how to test it with the whole github storage etc... Perhaps we can discuss this briefly tomorrow.

**Comment by RobbinBouwmeester** [comment]
@MartinRykaer , I think this is a good solution. I assume the infile is the intermediate file in your example?

I suggest to add it to the json as follows:

`{"0":{"id":"MSFragger_0_1675871800.835332","search_engine":"MSFragger","software_version":0,"fdr_psm":0,"fdr_peptide":0,"fdr_protein":0,"MBR":false,"precursor_tol":0,"precursor_tol_unit":"Da","fragmnent_tol":0,"fragment_tol_unit":"Da","enzyme_name":null,"missed_cleavages":0,"min_pep_length":0,"max_pep_length":0,"weighted_sum":46.944,"nr_prec":15612,"is_temporary":false,intermediate_file_hash:""},"1":{"id":"MaxQuant_0_1675871800.951341","search_engine":"MaxQuant","software_version":0,"fdr_psm":0,"fdr_peptide":0,"fdr_protein":0,"MBR":false,"precursor_tol":0,"precursor_tol_unit":"Da","fragmnent_tol":0,"fragment_tol_unit":"Da","enzyme_name":null,"missed_cleavages":0,"min_pep_length":0,"max_pep_length":0,"weighted_sum":45.838,"nr_prec":856,"is_temporary":false,intermediate_file_hash:""}}`

Note the:

`intermediate_file_hash:""`

In terms of what it returns, we can make a pop-up dialog that it clashed with a previous submission and information about what previous run it clashed with, something like:

`st.error(f"The run you want to submit has been previously submitted under the identifier: {clash_identifier}", icon="🚨")`

**Comment by RobbinBouwmeester** [comment]
Should be fixed in: #129
