### ISSUE TITLE
wrong link from module page to documentation

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#512]
**Describe the bug**
in the screenshot below, the link of "here" links to the DIA module doc. It should link to the DDA module: 
![image](https://github.com/user-attachments/assets/2aead987-9744-4ffe-88a9-8c4a9fba013a)

**Comment by mlocardpaulet** [comment]
@RobbinBouwmeester I don't understand why in `webinterface/pages/texts/generic_texts.py` the `doc_url` links to the DIA module help page. 
Shouldn't this be in `webinterface/pages/pages_variables/Quant/lfq/ion/DDA/variables.py`? And same for all modules?
This would also be valid for all the links in "Help" in the generic_texts.py

**Comment by RobbinBouwmeester** [comment]
Indeed, should now be fixed in #515
