### ISSUE TITLE
Add all Abstract Methods to the Interfaces

### ISSUE THREAD

**Issue by vedran-kasalica** [Proteobench/ProteoBench#55]
The classes currently implement Interfaces, so these interfaces should be updated. Each should list abstract methods that the main class should implement. Idea is that these methods provide a unified interface for interacting with each module.

**Comment by enryH** [comment]
I guess we could also use a Protocol, see for e.g. [this video](https://www.youtube.com/watch?v=xvb5hGLoK0A).

The basic idea is: Define using duck-typing an interface and then tell users to adhere to it using type hints.

**Comment by enryH** [comment]
So `ModuleInterface` and `ParseInputsInterface` should be moved from the `dda_quant` module to a more general types/interfaces module?

**Comment by enryH** [comment]
So `Datapoint`, `PlotDataPoint`, `ParseSettings` could also get an interface if these should be formalised

**Comment by vedran-kasalica** [comment]
> I guess we could also use a Protocol, see for e.g. [this video](https://www.youtube.com/watch?v=xvb5hGLoK0A).
> 
> The basic idea is: Define using duck-typing an interface and then tell users to adhere to it using type hints.

It's a nice video (I didn't know that Arjan is a YouTuber now, we used to work in the same group). I am not sure if Protocols are a better fit as they require fixed methods that will utilise them. And here we just want to structure (and guide the development of) the expected classes. Considering that we implemented abstract classes, maybe we can just stick to them for now.

> So `ModuleInterface` and `ParseInputsInterface` should be moved from the `dda_quant` module to a more general types/interfaces module?
> 
> As far as I see the [**init**.py](https://github.com/Proteobench/ProteoBench/blob/main/proteobench/modules/dda_quant/__init__.py) already contains the abstract classes.


ModuleInterface and ParseInputsInterface are also available in the `template` module [init.py](https://github.com/Proteobench/ProteoBench/blob/main/proteobench/modules/template/__init__.py). They should be removed from `dda_quant` init, and moved from `template` and put in a separate folder. The reason being if anyone copies `template` they will copy the abstract classes and potentially create their own versions.



> So `Datapoint`, `PlotDataPoint`, `ParseSettings` could also get an interface if these should be formalised

I agree.
