### ISSUE TITLE
Implement support for uploading (and storing) workflow configuration files

### ISSUE THREAD

**Issue by RalfG** [Proteobench/ProteoBench#58]
Next to structured and unstructured metadata, we would like to support the upload of configuration files (e.g., mqpar.xml) to be stored alongside the intermediate files and the metadata.

**Comment by enryH** [comment]
I had to parse a lot of parameter files for a submission into a table format. It is not yet a standalone module, but the functionality should be fairly general:

[Link to script to parse maxquant parameter files](https://github.com/RasmussenLab/pimms/blob/d9d6f1a3a12770bf6866ca78bef7ff3f1637167e/project/erda_05_parse_paramter_files.py)

**Comment by enryH** [comment]
Aim for now:
- populate automatically as many parameters as possible in the UI based on parameter files exported by search engines
  - e.g. based on `mqpar.xml` of MaxQuant
- in case the parameter file cannot be parsed, describe the problem, but continue running (manuell editing)

**Comment by mlocardpaulet** [comment]
I am making a table with the list of parameters that we want to keep, and their description. 
https://docs.google.com/spreadsheets/d/1Os3By8LYuVGcfH65X2-9tSjJnmtH-nL03tPYLtPOj-c/edit#gid=0

**Comment by enryH** [comment]
If you look at e.g. json and xml files in the `test/params` folder - https://github.com/Proteobench/ProteoBench/tree/parse_settings/test/params - an example mapping could be


our parameter name |  MaxQuant |
--- | ---
MS2 mass tolerance |  '["msmsParamsArray"][0]["MatchTolerance"]'
minimum peptide length | '["minPepLen"]'

**Comment by mlocardpaulet** [comment]
We noticed lack of consistency in the msfragger.params.toml file between the upper/lower tolerance bounds and the mass tolerance: 
```
precursor_mass_lower = -10			# Lower bound of the precursor mass window.
precursor_mass_upper = 10			# Upper bound of the precursor mass window.
precursor_mass_units = 1			# Precursor mass tolerance units (0 for Da, 1 for ppm).
precursor_true_tolerance = 20			# True precursor mass tolerance (window is +/- this value).
```
We need to contact the developers to ask how to deal with it.

**Comment by mlocardpaulet** [comment]
precursor_mass_lower and precursor_mass_upper is defined for some pre-searching step. We'll ignore them

**Comment by mlocardpaulet** [comment]
For FragPipe we need to contact the developers to ask where to find the parameters. We'll send an email when we have a define set of parameters that we need.

**Comment by enryH** [comment]
> I am making a table with the list of parameters that we want to keep, and their description. https://docs.google.com/spreadsheets/d/1Os3By8LYuVGcfH65X2-9tSjJnmtH-nL03tPYLtPOj-c/edit#gid=0

And here is the table Veit mentioned: [link](https://github.com/bigbio/proteomics-sample-metadata/blob/master/sdrf-proteomics/Data-analysis-metadata.adoc)

Potentially it could be a good idea to take their parameter naming to keep the projects in sync.

**Comment by mlocardpaulet** [comment]
Of course! I totally agree

**Comment by enryH** [comment]
@RobbinBouwmeester Can you show me the current [results.json](https://github.com/Proteobench/ProteoBench/blob/main/results.json)? The one I linked in the main folder on the main branch is seven months old and did not look like the one you showed.

**Comment by RobbinBouwmeester** [comment]
Yes, here it is: https://github.com/Proteobench/Results_Module2_quant_DDA/blob/main/results.json
