### ISSUE TITLE
Local development/deployment

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#61]
- Allow for easier local development and deployment
- Allow for local storage/adjustment of the json (flag for local; remove connection to github)
- Sharing of .secret if development is local, and connection to github for submission

**Comment by vedran-kasalica** [comment]
1) Using GitHub secrets (https://github.com/Proteobench/ProteoBench/settings/secrets/codespaces) might be a good option to store .secret. I will look into it. 

2) Regarding local development, maybe we can set a parameter, that determines whether the deployed website writes to GitHub or to a local file (or local version of Results_Module2_quant_DDA) that we can use to load the data as well.

Note:
Maybe this should be split into 2 issues, as .secret would not be used for local development.

**Comment by RobbinBouwmeester** [comment]
> 1. Using GitHub secrets (https://github.com/Proteobench/ProteoBench/settings/secrets/codespaces) might be a good option to store .secret. I will look into it.
> 
>     2. Regarding local development, maybe we can set a parameter, that determines whether the deployed website writes to GitHub or to a local file (or local version of Results_Module2_quant_DDA) that we can use to load the data as well.
> 
> 
> Note: Maybe this should be split into 2 issues, as .secret would not be used for local development.

Agreed, should be separate issues.

**Comment by vedran-kasalica** [comment]
GitHub secrets are used in combination with GitHub Actions (it is not meant for sharing secrets), so it would be an option once we setup CI, but not before.
