### ISSUE TITLE
plot DDA quan: make the locally loaded search result stand out

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#75]

**Comment by enryH** [comment]
Make a newly entered result stand out

**Comment by mlocardpaulet** [comment]
Unless I am mistaken, this does not work anymore. In the few tests I made (with MQ and MSFragger), there is no point that appears bigger in the plot.

**Comment by mlocardpaulet** [comment]
So... this does not seem to be an issue anymore. At least in the last version that I pulled. I don't know why I had the issue the other day.
