### ISSUE TITLE
add tool-specific instructions

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#80]
when a search engine / tool is selected, we should see the specific instructions that correspond to the tool. For example, in MQ it is  imperative that the users uncheck the contaminants. In Proline, we currently only support the tsv imports of the quantified ions etc...

**Comment by mlocardpaulet** [comment]
instructions/information are currently stored here: https://docs.google.com/document/d/1cnG5q-muU8C07NYFHVtN5e8GXNByPQn4ceu6H1497zw/edit

**Comment by RobbinBouwmeester** [comment]
@RalfG, can you indicate how this can be added to the documentation?

**Comment by mlocardpaulet** [comment]
I have added information in the documents that @RalfG set up in `docs/modules`. It is hidden right now, and I am not sure how it should be set up so that we can access it directly from the module webinterface.
