### ISSUE TITLE
module Vs tool .toml files

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#84]
Right now the tool .toml files (MQ, AlphaPept...) contain information on how to parse the input tables (run name, column headers...) AND information about the module (expected ratio).
We should have:
- toml files that contain only parsing information 
- one toml file per module that contain the module information 

Also, right now the toml are named with the tool name, maybe we also want to include information of the input file (evidence, peptidegroup etc... for MQ for example) that it corresponds to. Because in the end there will be several toml files for MQ.

**Comment by mlocardpaulet** [comment]
Maybe we should also add in .toml file the name of the parsed file (evidence.txt, peptides.txt...)

**Comment by mlocardpaulet** [comment]
BTW, here is the list of the input files that we want to parse for each module:
https://docs.google.com/spreadsheets/d/1J_SVlD879Z8fG2SRwCmvwZ7-b3qXGn3kz3aPuW23RFY/edit#gid=0

**Comment by mlocardpaulet** [comment]
Also, in all the toml files we kept "LFQ_Orbitrap..." in the run_mapper. I guess it is because it was copied/pasted from MQ. We should only keep "Condition_A_Sample_Alpha_03" etc...

**Comment by RobbinBouwmeester** [comment]
Fixed in [https://github.com/Proteobench/ProteoBench/pull/112](https://github.com/Proteobench/ProteoBench/pull/112)
