### ISSUE TITLE
make documentation for .toml files

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#88]
document that describes what should be in the parsing toml files:
https://docs.google.com/document/d/10Dw4SZeRaMDNjsDeUIHG6q9S4V8WfMEeaQQULjXn9Go/edit?usp=sharing

**Comment by RobbinBouwmeester** [comment]
@RalfG can you help with adding this documentation?

**Comment by mlocardpaulet** [comment]
It is here: https://proteobench.readthedocs.io/en/latest/modules/3-DDA-Quantification-ion-level/#toml-file-description
we can move it if it is not in the best location.
