### ISSUE TITLE
Send link to pull request proteobot

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#97]

**Comment by RobbinBouwmeester** [comment]
@viikiid you were working on this too, right?

**Comment by viikiid** [comment]
yes, however I only got to the point that I could read the commit number but not the generated pull request ID

**Comment by RobbinBouwmeester** [comment]
Should be fixed in: https://github.com/Proteobench/ProteoBench/pull/155
